--------------------------------------------------------
--  File created - Monday-November-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CAMPAIGN
--------------------------------------------------------

   CREATE SEQUENCE  "DONASI"."SEQ_CAMPAIGN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DONASI
--------------------------------------------------------

   CREATE SEQUENCE  "DONASI"."SEQ_DONASI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DONATUR
--------------------------------------------------------

   CREATE SEQUENCE  "DONASI"."SEQ_DONATUR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LAPORAN
--------------------------------------------------------

   CREATE SEQUENCE  "DONASI"."SEQ_LAPORAN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PEMBAYARAN
--------------------------------------------------------

   CREATE SEQUENCE  "DONASI"."SEQ_PEMBAYARAN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PENERIMA
--------------------------------------------------------

   CREATE SEQUENCE  "DONASI"."SEQ_PENERIMA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CAMPAIGN
--------------------------------------------------------

  CREATE TABLE "DONASI"."CAMPAIGN" 
   (	"ID_CAMPAIGN" NUMBER, 
	"ID_PENERIMA" NUMBER, 
	"JUDUL_CAMPAIGN" VARCHAR2(255 BYTE), 
	"DESKRIPSI" CLOB, 
	"TARGET_DANA" NUMBER(12,2), 
	"DANA_TERKUMPUL" NUMBER(12,2) DEFAULT 0, 
	"TANGGAL_MULAI" DATE, 
	"TANGGAL_DEADLINE" DATE, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'Aktif', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESKRIPSI") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DONASI
--------------------------------------------------------

  CREATE TABLE "DONASI"."DONASI" 
   (	"ID_DONASI" NUMBER, 
	"ID_DONATUR" NUMBER, 
	"ID_CAMPAIGN" NUMBER, 
	"JUMLAH_DONASI" NUMBER(10,2), 
	"PESAN_DONATUR" CLOB, 
	"IS_ANONIM" NUMBER(1,0) DEFAULT 0, 
	"TANGGAL_DONASI" DATE DEFAULT SYSDATE, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE, 
	"METODE" VARCHAR2(50 BYTE), 
	"PESAN" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PESAN_DONATUR") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DONATUR
--------------------------------------------------------

  CREATE TABLE "DONASI"."DONATUR" 
   (	"ID_DONATUR" NUMBER, 
	"NAMA_DONATUR" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"NOMOR_TELEPON" VARCHAR2(15 BYTE), 
	"TANGGAL_TERDAFTAR" DATE DEFAULT SYSDATE, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE, 
	"PASSWORD_HASH" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LAPORAN
--------------------------------------------------------

  CREATE TABLE "DONASI"."LAPORAN" 
   (	"ID_LAPORAN" NUMBER, 
	"ID_CAMPAIGN" NUMBER, 
	"ID_PENERIMA" NUMBER, 
	"JUDUL_LAPORAN" VARCHAR2(255 BYTE), 
	"ISI_LAPORAN" CLOB, 
	"TANGGAL_GENERATE" DATE DEFAULT SYSDATE, 
	"TOTAL_DANA_TERKUMPUL" NUMBER(12,2), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ISI_LAPORAN") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table PEMBAYARAN
--------------------------------------------------------

  CREATE TABLE "DONASI"."PEMBAYARAN" 
   (	"ID_PEMBAYARAN" NUMBER, 
	"ID_DONASI" NUMBER, 
	"KODE_TRANSAKSI" VARCHAR2(50 BYTE), 
	"METODE_PEMBAYARAN" VARCHAR2(50 BYTE), 
	"STATUS_BAYAR" VARCHAR2(20 BYTE) DEFAULT 'Pending', 
	"TANGGAL_PEMBAYARAN" DATE DEFAULT SYSDATE, 
	"BIAYA_ADMIN" NUMBER(5,2) DEFAULT 0, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PENERIMA
--------------------------------------------------------

  CREATE TABLE "DONASI"."PENERIMA" 
   (	"ID_PENERIMA" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View VW_CAMPAIGN_SUMMARY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DONASI"."VW_CAMPAIGN_SUMMARY" ("ID_CAMPAIGN", "JUDUL_CAMPAIGN", "PENERIMA_USERNAME", "TARGET_DANA", "DANA_TERKUMPUL", "PERSENTASE_TARGET", "STATUS", "TANGGAL_MULAI", "TANGGAL_DEADLINE", "HARI_TERSISA", "JUMLAH_DONATUR") AS 
  SELECT 
    c.id_campaign,
    c.judul_campaign,
    p.username AS penerima_username,
    c.target_dana,
    c.dana_terkumpul,
    ROUND((c.dana_terkumpul / c.target_dana) * 100, 2) AS persentase_target,
    c.status,
    c.tanggal_mulai,
    c.tanggal_deadline,
    TRUNC(c.tanggal_deadline - SYSDATE) AS hari_tersisa,
    COUNT(d.id_donasi) AS jumlah_donatur
FROM campaign c
LEFT JOIN penerima p ON c.id_penerima = p.id_penerima
LEFT JOIN donasi d ON c.id_campaign = d.id_campaign
GROUP BY c.id_campaign, c.judul_campaign, p.username, c.target_dana, 
         c.dana_terkumpul, c.status, c.tanggal_mulai, c.tanggal_deadline
;
--------------------------------------------------------
--  DDL for View VW_DONASI_DETAIL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DONASI"."VW_DONASI_DETAIL" ("ID_CAMPAIGN", "JUDUL_CAMPAIGN", "ID_DONASI", "NAMA_DONATUR", "EMAIL_DONATUR", "JUMLAH_DONASI", "PESAN_DONATUR", "STATUS_BAYAR", "TANGGAL_DONASI") AS 
  SELECT 
    c.id_campaign,
    c.judul_campaign,
    d.id_donasi,
    DECODE(d.is_anonim, 1, 'Anonymous', dr.nama_donatur) AS nama_donatur,
    dr.email AS email_donatur,
    d.jumlah_donasi,
    d.pesan_donatur,
    pb.status_bayar,
    d.tanggal_donasi
FROM donasi d
LEFT JOIN donatur dr ON d.id_donatur = dr.id_donatur
LEFT JOIN campaign c ON d.id_campaign = c.id_campaign
LEFT JOIN pembayaran pb ON d.id_donasi = pb.id_donasi
;
REM INSERTING into DONASI.CAMPAIGN
SET DEFINE OFF;
Insert into DONASI.CAMPAIGN (ID_CAMPAIGN,ID_PENERIMA,JUDUL_CAMPAIGN,TARGET_DANA,DANA_TERKUMPUL,TANGGAL_MULAI,TANGGAL_DEADLINE,STATUS,CREATED_AT,UPDATED_AT) values ('21','1','apaaa','1400000000','21000001',to_date('13-11-2025','DD-MM-RRRR'),to_date('13-12-2025','DD-MM-RRRR'),'Aktif',to_date('13-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'));
Insert into DONASI.CAMPAIGN (ID_CAMPAIGN,ID_PENERIMA,JUDUL_CAMPAIGN,TARGET_DANA,DANA_TERKUMPUL,TANGGAL_MULAI,TANGGAL_DEADLINE,STATUS,CREATED_AT,UPDATED_AT) values ('1','1','donasi untuk gempa bumi','1400000','14000000',to_date('08-11-2025','DD-MM-RRRR'),to_date('08-12-2025','DD-MM-RRRR'),'Aktif',to_date('08-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'));
REM INSERTING into DONASI.DONASI
SET DEFINE OFF;
Insert into DONASI.DONASI (ID_DONASI,ID_DONATUR,ID_CAMPAIGN,JUMLAH_DONASI,IS_ANONIM,TANGGAL_DONASI,CREATED_AT,UPDATED_AT,METODE,PESAN) values ('6',null,'21','7000000','1',to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),'Transfer Bank','gg');
Insert into DONASI.DONASI (ID_DONASI,ID_DONATUR,ID_CAMPAIGN,JUMLAH_DONASI,IS_ANONIM,TANGGAL_DONASI,CREATED_AT,UPDATED_AT,METODE,PESAN) values ('7',null,'1','7000000','1',to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),'Transfer Bank','gg');
Insert into DONASI.DONASI (ID_DONASI,ID_DONATUR,ID_CAMPAIGN,JUMLAH_DONASI,IS_ANONIM,TANGGAL_DONASI,CREATED_AT,UPDATED_AT,METODE,PESAN) values ('3','41','21','7000000','0',to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),'E-Wallet',null);
Insert into DONASI.DONASI (ID_DONASI,ID_DONATUR,ID_CAMPAIGN,JUMLAH_DONASI,IS_ANONIM,TANGGAL_DONASI,CREATED_AT,UPDATED_AT,METODE,PESAN) values ('8',null,'21','7000000','1',to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),'Transfer Bank','gg');
Insert into DONASI.DONASI (ID_DONASI,ID_DONATUR,ID_CAMPAIGN,JUMLAH_DONASI,IS_ANONIM,TANGGAL_DONASI,CREATED_AT,UPDATED_AT,METODE,PESAN) values ('9',null,'1','7000000','1',to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),'Transfer Bank','gg');
Insert into DONASI.DONASI (ID_DONASI,ID_DONATUR,ID_CAMPAIGN,JUMLAH_DONASI,IS_ANONIM,TANGGAL_DONASI,CREATED_AT,UPDATED_AT,METODE,PESAN) values ('10','26','21','1','0',to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),null,null);
REM INSERTING into DONASI.DONATUR
SET DEFINE OFF;
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('26','ces','ibad20@gmail.com',null,to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),'$2y$10$IYF8JM/fLuJVcX1MVLXqSuxIqgoNN.7UBh7cAaORrEDSBL9VnlRry');
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('2','admin12','admin12@gmail.com','0987654321',to_date('08-11-2025','DD-MM-RRRR'),to_date('08-11-2025','DD-MM-RRRR'),to_date('08-11-2025','DD-MM-RRRR'),null);
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('41','Donatur Anonim','anonim@donasi.local',null,to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),to_date('16-11-2025','DD-MM-RRRR'),null);
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('1','admin','admin@gmail.com','12345678901',to_date('08-11-2025','DD-MM-RRRR'),to_date('08-11-2025','DD-MM-RRRR'),to_date('08-11-2025','DD-MM-RRRR'),null);
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('23','poco','poco@gmail.com',null,to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),'$2y$10$9a8zxpUxDdhj8I4g3YSZquATbObhP126AaIIfDepCONsWiIr17Lri    ');
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('24','admin21','admin21@gmail.com',null,to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),'$2y$10$k4n/tpGQCpEu7lg5m8gKY.p2qIo1ZopsbnRU1a2eGAPCYhmdwPROW    ');
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('25','kaca','aca@gmail.com',null,to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),'$2y$10$mdhXOv2bDuWU9rA/EmCLWOg1yqNkCr0VZA9ajcZptJDoeWIBGQJue');
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('3','kensato','kensato@gmail.com','122233334444',to_date('08-11-2025','DD-MM-RRRR'),to_date('08-11-2025','DD-MM-RRRR'),to_date('08-11-2025','DD-MM-RRRR'),'52284d0a4d012a8c47fb008f2f099662641798b2deca757753941e83ce086558');
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('21','Irsyadul Ibad','kipas@gmail.com',null,to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),'$2y$10$sFZvI3IJMJzgbQ5xAtqu.e76eRwBTCZQRLEWzsv4TUYmwC4zu5OT6    ');
Insert into DONASI.DONATUR (ID_DONATUR,NAMA_DONATUR,EMAIL,NOMOR_TELEPON,TANGGAL_TERDAFTAR,CREATED_AT,UPDATED_AT,PASSWORD_HASH) values ('22','usb','test@gmail.com',null,to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'),'$2y$10$RruoSfbMz1OZnHw0n5n5ceYtwnyfm/URZG9bKbxc0I1TJaMXiXls2    ');
REM INSERTING into DONASI.LAPORAN
SET DEFINE OFF;
REM INSERTING into DONASI.PEMBAYARAN
SET DEFINE OFF;
REM INSERTING into DONASI.PENERIMA
SET DEFINE OFF;
Insert into DONASI.PENERIMA (ID_PENERIMA,USERNAME,EMAIL,PASSWORD_HASH,CREATED_AT,UPDATED_AT) values ('1','admin','admin@gmail.com','332d925bf2bdb82432038fea76db8b3dbe52161275632e5dc403fb2e867b3c7b',to_date('08-11-2025','DD-MM-RRRR'),to_date('08-11-2025','DD-MM-RRRR'));
Insert into DONASI.PENERIMA (ID_PENERIMA,USERNAME,EMAIL,PASSWORD_HASH,CREATED_AT,UPDATED_AT) values ('23','kensato','kensato@gmail.com','$2y$10$.QfuV2FeBKcNIGfKefvHJO7l/Gw52/WzNo1eSrxwLngLaJqdhPpta',to_date('11-11-2025','DD-MM-RRRR'),to_date('11-11-2025','DD-MM-RRRR'));
--------------------------------------------------------
--  DDL for Index IDX_CAMPAIGN_TANGGAL
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_CAMPAIGN_TANGGAL" ON "DONASI"."CAMPAIGN" ("TANGGAL_MULAI", "TANGGAL_DEADLINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_LAPORAN_PENERIMA
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_LAPORAN_PENERIMA" ON "DONASI"."LAPORAN" ("ID_PENERIMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_DONASI_DONATUR
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_DONASI_DONATUR" ON "DONASI"."DONASI" ("ID_DONATUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_LAPORAN_CAMPAIGN
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_LAPORAN_CAMPAIGN" ON "DONASI"."LAPORAN" ("ID_CAMPAIGN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PEMBAYARAN_STATUS
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_PEMBAYARAN_STATUS" ON "DONASI"."PEMBAYARAN" ("STATUS_BAYAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_DONASI_CAMPAIGN
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_DONASI_CAMPAIGN" ON "DONASI"."DONASI" ("ID_CAMPAIGN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_DONATUR_NAMA
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_DONATUR_NAMA" ON "DONASI"."DONATUR" ("NAMA_DONATUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_CAMPAIGN_PENERIMA
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_CAMPAIGN_PENERIMA" ON "DONASI"."CAMPAIGN" ("ID_PENERIMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_LAPORAN_TANGGAL
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_LAPORAN_TANGGAL" ON "DONASI"."LAPORAN" ("TANGGAL_GENERATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_DONASI_TANGGAL
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_DONASI_TANGGAL" ON "DONASI"."DONASI" ("TANGGAL_DONASI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PEMBAYARAN_DONASI
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_PEMBAYARAN_DONASI" ON "DONASI"."PEMBAYARAN" ("ID_DONASI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_CAMPAIGN_STATUS
--------------------------------------------------------

  CREATE INDEX "DONASI"."IDX_CAMPAIGN_STATUS" ON "DONASI"."CAMPAIGN" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_CAMPAIGN_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DONASI"."TRG_CAMPAIGN_UPDATE" 
BEFORE UPDATE ON campaign
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

/
ALTER TRIGGER "DONASI"."TRG_CAMPAIGN_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DONASI_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DONASI"."TRG_DONASI_UPDATE" 
BEFORE UPDATE ON donasi
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

/
ALTER TRIGGER "DONASI"."TRG_DONASI_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DONATUR_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DONASI"."TRG_DONATUR_UPDATE" 
BEFORE UPDATE ON donatur
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

/
ALTER TRIGGER "DONASI"."TRG_DONATUR_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_LAPORAN_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DONASI"."TRG_LAPORAN_UPDATE" 
BEFORE UPDATE ON laporan
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

/
ALTER TRIGGER "DONASI"."TRG_LAPORAN_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PEMBAYARAN_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DONASI"."TRG_PEMBAYARAN_UPDATE" 
BEFORE UPDATE ON pembayaran
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

/
ALTER TRIGGER "DONASI"."TRG_PEMBAYARAN_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PENERIMA_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DONASI"."TRG_PENERIMA_UPDATE" 
BEFORE UPDATE ON penerima
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;

/
ALTER TRIGGER "DONASI"."TRG_PENERIMA_UPDATE" ENABLE;
--------------------------------------------------------
--  Constraints for Table PEMBAYARAN
--------------------------------------------------------

  ALTER TABLE "DONASI"."PEMBAYARAN" MODIFY ("ID_DONASI" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PEMBAYARAN" MODIFY ("KODE_TRANSAKSI" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PEMBAYARAN" MODIFY ("METODE_PEMBAYARAN" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PEMBAYARAN" MODIFY ("STATUS_BAYAR" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PEMBAYARAN" MODIFY ("TANGGAL_PEMBAYARAN" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PEMBAYARAN" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PEMBAYARAN" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PEMBAYARAN" ADD CHECK (status_bayar IN ('Pending', 'Sukses', 'Gagal')) ENABLE;
 
  ALTER TABLE "DONASI"."PEMBAYARAN" ADD PRIMARY KEY ("ID_PEMBAYARAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DONASI"."PEMBAYARAN" ADD UNIQUE ("KODE_TRANSAKSI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAMPAIGN
--------------------------------------------------------

  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("ID_PENERIMA" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("JUDUL_CAMPAIGN" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("DESKRIPSI" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("TARGET_DANA" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("DANA_TERKUMPUL" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("TANGGAL_MULAI" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("TANGGAL_DEADLINE" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."CAMPAIGN" ADD CHECK (status IN ('Aktif', 'Selesai', 'Ditangguhkan')) ENABLE;
 
  ALTER TABLE "DONASI"."CAMPAIGN" ADD PRIMARY KEY ("ID_CAMPAIGN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LAPORAN
--------------------------------------------------------

  ALTER TABLE "DONASI"."LAPORAN" MODIFY ("ID_CAMPAIGN" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."LAPORAN" MODIFY ("ID_PENERIMA" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."LAPORAN" MODIFY ("JUDUL_LAPORAN" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."LAPORAN" MODIFY ("ISI_LAPORAN" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."LAPORAN" MODIFY ("TANGGAL_GENERATE" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."LAPORAN" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."LAPORAN" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."LAPORAN" ADD PRIMARY KEY ("ID_LAPORAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DONATUR
--------------------------------------------------------

  ALTER TABLE "DONASI"."DONATUR" MODIFY ("NAMA_DONATUR" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONATUR" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONATUR" MODIFY ("TANGGAL_TERDAFTAR" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONATUR" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONATUR" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONATUR" ADD PRIMARY KEY ("ID_DONATUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DONASI"."DONATUR" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PENERIMA
--------------------------------------------------------

  ALTER TABLE "DONASI"."PENERIMA" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PENERIMA" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PENERIMA" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PENERIMA" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PENERIMA" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."PENERIMA" ADD PRIMARY KEY ("ID_PENERIMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DONASI"."PENERIMA" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DONASI"."PENERIMA" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DONASI
--------------------------------------------------------

  ALTER TABLE "DONASI"."DONASI" MODIFY ("ID_CAMPAIGN" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONASI" MODIFY ("JUMLAH_DONASI" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONASI" MODIFY ("TANGGAL_DONASI" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONASI" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONASI" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DONASI"."DONASI" ADD PRIMARY KEY ("ID_DONASI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAMPAIGN
--------------------------------------------------------

  ALTER TABLE "DONASI"."CAMPAIGN" ADD CONSTRAINT "FK_CAMPAIGN_PENERIMA" FOREIGN KEY ("ID_PENERIMA")
	  REFERENCES "DONASI"."PENERIMA" ("ID_PENERIMA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DONASI
--------------------------------------------------------

  ALTER TABLE "DONASI"."DONASI" ADD CONSTRAINT "FK_DONASI_CAMPAIGN" FOREIGN KEY ("ID_CAMPAIGN")
	  REFERENCES "DONASI"."CAMPAIGN" ("ID_CAMPAIGN") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "DONASI"."DONASI" ADD CONSTRAINT "FK_DONASI_DONATUR" FOREIGN KEY ("ID_DONATUR")
	  REFERENCES "DONASI"."DONATUR" ("ID_DONATUR") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LAPORAN
--------------------------------------------------------

  ALTER TABLE "DONASI"."LAPORAN" ADD CONSTRAINT "FK_LAPORAN_CAMPAIGN" FOREIGN KEY ("ID_CAMPAIGN")
	  REFERENCES "DONASI"."CAMPAIGN" ("ID_CAMPAIGN") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "DONASI"."LAPORAN" ADD CONSTRAINT "FK_LAPORAN_PENERIMA" FOREIGN KEY ("ID_PENERIMA")
	  REFERENCES "DONASI"."PENERIMA" ("ID_PENERIMA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEMBAYARAN
--------------------------------------------------------

  ALTER TABLE "DONASI"."PEMBAYARAN" ADD CONSTRAINT "FK_PEMBAYARAN_DONASI" FOREIGN KEY ("ID_DONASI")
	  REFERENCES "DONASI"."DONASI" ("ID_DONASI") ON DELETE CASCADE ENABLE;
